Run("C:\Program Files (x86)\Microsoft Office\Office14\OUTLOOK.EXE /recycle")
Sleep(10000)
WinWaitActive("收件箱 - PANGBAIMEI128@pingan.com.cn - Microsoft Outlook")
Send("^n")
WinWaitActive("未命名 - 邮件 (HTML) ")
ControlSend("未命名 - 邮件 (HTML) ","","RichEdit20WPT1","ZHANGMIN475@pingan.com.cn;LIANGXUQING353@pingan.com.cn;WANDING286@pingan.com.cn;LUOJINGJING888@pingan.com.cn;PANGBAIMEI128@pingan.com.cn","1")
Sleep(2000)
ControlSend("未命名 - 邮件 (HTML) ","","RichEdit20WPT4","Web自动化测试报告","1")
Sleep(2000)
$content = "本次执行，详细执行情况：http://JKQSH-L0056:8080/jenkins/userContent/yztRegister-reporter/test-reporter/report.html"
ControlFocus("未命名 - 邮件 (HTML) ","","_WwG1")
ControlSend("未命名 - 邮件 (HTML) ","","_WwG1",$content,"1")
Sleep(2000)
ControlFocus("未命名 - 邮件 (HTML) ","发送(&S)","Button1")
ControlClick("未命名 - 邮件 (HTML) ","发送(&S)","Button1")